import { APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { buildCorsHeadersAsync } from '../../shared/utils/cors';
import {
  ayrshareAutoHashtag,
  ayrshareRecommendHashtags,
  ayrshareSearchHashtags,
  ayrshareCheckBannedHashtags,
} from './ayrshare-client';

const API_KEY = process.env.AYRSHARE_API_KEY!;

export const handler = async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
  const corsHeaders = await buildCorsHeadersAsync({ allowMethods: ['OPTIONS', 'POST', 'GET'] }, event.headers?.origin || event.headers?.Origin);

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers: corsHeaders, body: '' };
  }

  try {
    const path = event.path;
    const method = event.httpMethod;

    // ---------------------------------------------------------
    // POST /hashtags/auto - Auto-generate hashtags for text
    // ---------------------------------------------------------
    if (path.includes('/auto') && method === 'POST') {
      const body = JSON.parse(event.body || '{}');
      const { text, max = 5, position = 'end' } = body;

      if (!text) {
        return {
          statusCode: 400,
          headers: corsHeaders,
          body: JSON.stringify({ success: false, error: 'text is required' })
        };
      }

      const result = await ayrshareAutoHashtag(API_KEY, text, max, position);

      return {
        statusCode: 200,
        headers: corsHeaders,
        body: JSON.stringify({
          success: true,
          originalText: text,
          modifiedText: result.post || result.text || text,
          hashtags: result.hashtags || [],
          autoGenerated: true
        })
      };
    }

    // ---------------------------------------------------------
    // GET /hashtags/recommend - Get hashtag recommendations
    // ---------------------------------------------------------
    if (path.includes('/recommend') && method === 'GET') {
      const keyword = event.queryStringParameters?.keyword;
      const limit = parseInt(event.queryStringParameters?.limit || '10');

      if (!keyword) {
        return {
          statusCode: 400,
          headers: corsHeaders,
          body: JSON.stringify({ success: false, error: 'keyword is required' })
        };
      }

      const result = await ayrshareRecommendHashtags(API_KEY, keyword, limit);

      return {
        statusCode: 200,
        headers: corsHeaders,
        body: JSON.stringify({
          success: true,
          keyword,
          recommendations: result.hashtags || result || []
        })
      };
    }

    // ---------------------------------------------------------
    // GET /hashtags/search - Search hashtags on a platform
    // ---------------------------------------------------------
    if (path.includes('/search') && method === 'GET') {
      const query = event.queryStringParameters?.query;
      const platform = event.queryStringParameters?.platform || 'instagram';

      if (!query) {
        return {
          statusCode: 400,
          headers: corsHeaders,
          body: JSON.stringify({ success: false, error: 'query is required' })
        };
      }

      const result = await ayrshareSearchHashtags(API_KEY, query, platform);

      return {
        statusCode: 200,
        headers: corsHeaders,
        body: JSON.stringify({
          success: true,
          query,
          platform,
          results: result.hashtags || result || []
        })
      };
    }

    // ---------------------------------------------------------
    // GET /hashtags/check-banned - Check if hashtags are banned
    // ---------------------------------------------------------
    if (path.includes('/check-banned') && method === 'GET') {
      const hashtagsParam = event.queryStringParameters?.hashtags;

      if (!hashtagsParam) {
        return {
          statusCode: 400,
          headers: corsHeaders,
          body: JSON.stringify({ success: false, error: 'hashtags parameter is required' })
        };
      }

      const hashtags = hashtagsParam.split(',').map(h => h.trim());
      const result = await ayrshareCheckBannedHashtags(API_KEY, hashtags);

      return {
        statusCode: 200,
        headers: corsHeaders,
        body: JSON.stringify({
          success: true,
          hashtags,
          banned: result.banned || [],
          safe: result.safe || hashtags.filter((h: string) => !(result.banned || []).includes(h))
        })
      };
    }

    return {
      statusCode: 404,
      headers: corsHeaders,
      body: JSON.stringify({ error: 'Route not found' })
    };

  } catch (err: any) {
    console.error('Hashtags Error:', err);
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({
        success: false,
        error: err.message,
        code: 'HASHTAGS_ERROR'
      })
    };
  }
};
