/**
 * Google Ads OAuth Token Generator
 * 
 * This script generates the refresh token needed for Google Ads API authentication.
 * Run this script locally to complete the OAuth flow and get your refresh token.
 * 
 * Usage:
 *   npx ts-node scripts/generate-google-ads-token.ts
 * 
 * Prerequisites:
 *   npm install googleapis open
 */

import { google } from 'googleapis';
import * as http from 'http';
import * as url from 'url';
import * as fs from 'fs';
import * as path from 'path';

// Google Ads API credentials
const CLIENT_ID = '584598112747-e6oc5dku2m7bk6m8eirn9lg4ipg0t59k.apps.googleusercontent.com';
const CLIENT_SECRET = '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';
const DEVELOPER_TOKEN = 'yf0wVh6n6pkts1inzKFP_w';
const LOGIN_CUSTOMER_ID = '6325322362';

// OAuth2 configuration
const REDIRECT_URI = 'http://localhost:8080/oauth2callback';
const SCOPES = ['https://www.googleapis.com/auth/adwords'];

async function generateRefreshToken(): Promise<void> {
  console.log('='.repeat(60));
  console.log('Google Ads OAuth Token Generator');
  console.log('='.repeat(60));
  console.log();

  // Create OAuth2 client
  const oauth2Client = new google.auth.OAuth2(
    CLIENT_ID,
    CLIENT_SECRET,
    REDIRECT_URI
  );

  // Generate authorization URL
  const authUrl = oauth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
    prompt: 'consent', // Force consent to get refresh token
  });

  console.log('Opening browser for authentication...');
  console.log();
  console.log('If browser does not open, visit this URL manually:');
  console.log('-'.repeat(60));
  console.log(authUrl);
  console.log('-'.repeat(60));
  console.log();

  // Open browser
  const open = await import('open');
  await open.default(authUrl);

  // Start local server to receive callback
  const authCode = await new Promise<string>((resolve, reject) => {
    const server = http.createServer(async (req, res) => {
      try {
        const reqUrl = url.parse(req.url || '', true);
        
        if (reqUrl.pathname === '/oauth2callback') {
          const code = reqUrl.query.code as string;
          
          if (code) {
            res.writeHead(200, { 'Content-Type': 'text/html' });
            res.end(`
              <html>
                <body style="font-family: Arial, sans-serif; padding: 40px; text-align: center;">
                  <h1 style="color: #4CAF50;">✓ Authorization Successful!</h1>
                  <p>You can close this window and return to the terminal.</p>
                </body>
              </html>
            `);
            server.close();
            resolve(code);
          } else {
            const error = reqUrl.query.error as string;
            res.writeHead(400, { 'Content-Type': 'text/html' });
            res.end(`
              <html>
                <body style="font-family: Arial, sans-serif; padding: 40px; text-align: center;">
                  <h1 style="color: #f44336;">✗ Authorization Failed</h1>
                  <p>Error: ${error || 'Unknown error'}</p>
                </body>
              </html>
            `);
            server.close();
            reject(new Error(error || 'Authorization failed'));
          }
        }
      } catch (err) {
        reject(err);
      }
    });

    server.listen(8080, () => {
      console.log('Waiting for authorization...');
    });

    // Timeout after 5 minutes
    setTimeout(() => {
      server.close();
      reject(new Error('Authorization timeout'));
    }, 5 * 60 * 1000);
  });

  // Exchange code for tokens
  console.log();
  console.log('Exchanging authorization code for tokens...');
  
  const { tokens } = await oauth2Client.getToken(authCode);
  
  console.log();
  console.log('='.repeat(60));
  console.log('SUCCESS! OAuth tokens generated.');
  console.log('='.repeat(60));
  console.log();
  
  console.log('REFRESH TOKEN (copy this to global-secrets.json):');
  console.log('-'.repeat(60));
  console.log(tokens.refresh_token);
  console.log('-'.repeat(60));
  console.log();
  
  console.log('ACCESS TOKEN (for testing - expires in 1 hour):');
  console.log('-'.repeat(60));
  console.log(tokens.access_token);
  console.log('-'.repeat(60));
  console.log();

  // Create google-ads.yaml config file
  const yamlConfig = `# Google Ads API Configuration
# Generated by generate-google-ads-token.ts

developer_token: "${DEVELOPER_TOKEN}"
client_id: "${CLIENT_ID}"
client_secret: "${CLIENT_SECRET}"
refresh_token: "${tokens.refresh_token}"
login_customer_id: "${LOGIN_CUSTOMER_ID}"
use_proto_plus: true
`;

  const yamlPath = path.join(__dirname, '..', 'google-ads.yaml');
  fs.writeFileSync(yamlPath, yamlConfig);
  console.log(`Created google-ads.yaml at: ${yamlPath}`);
  console.log();

  // Output instructions
  console.log('='.repeat(60));
  console.log('NEXT STEPS:');
  console.log('='.repeat(60));
  console.log();
  console.log('1. Copy the REFRESH TOKEN above');
  console.log();
  console.log('2. Update global-secrets.json:');
  console.log('   Find the entry with "secretType": "refresh_token"');
  console.log('   Replace "NEEDS_OAUTH_GENERATION" with the refresh token');
  console.log();
  console.log('3. Deploy the CDK stack to update AWS Secrets Manager');
  console.log();
}

// Main
generateRefreshToken()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('Error:', error.message);
    console.log();
    console.log('If you see "redirect_uri_mismatch" error:');
    console.log('1. Go to Google Cloud Console > APIs & Services > Credentials');
    console.log('2. Edit your OAuth 2.0 Client ID');
    console.log('3. Add "http://localhost:8080/oauth2callback" to Authorized redirect URIs');
    console.log('4. Save and try again');
    process.exit(1);
  });
